### ISSUE TITLE
Laravel 8 + cache config issue

### ISSUE THREAD

**Issue by mnabialek** [beyondcode/laravel-self-diagnosis#103]
It seems there is problem with `ExampleEnvironmentVariablesAreSet` and Laravel 8.

Before upgrade, when I had config cached this checker was working without any problem. But after upgrade to Laravel 8, it shows that all variables are missing in .env file but are defined in .env.example when I have config cached. 

But when I run `php artisan config:clear` then checker is working fine again.

**Comment by ffmit** [comment]
I had the exact same behaviour.

**Comment by jargoud** [comment]
Hello,

Same behaviour here too.

I found a workaround by replacing:

```php
$actual = Dotenv::createImmutable(base_path(), '.env');
```

with:

```php
$actual = Dotenv::createMutable(base_path(), '.env');
```

in `checkForDotEnvV4` method (because it's a private method, I needed to override the class, `$envVariables` property and `check`, `checkForDotEnvV4` and `message` methods).

I didn't create a pull request yet, because I don't know (and didn't investigate on) the consequences of such a change in the code, but maybe it can unlock some other devs!

Regards,

Jeremy
