### ISSUE TITLE
[Question] about testing

### ISSUE THREAD

**Issue by tvbeek** [beyondcode/laravel-self-diagnosis#39]
There isn't a lot of tests in this project, but I see it in the requirements for the project. So I suspect it is on the to do list.

I like to add some test but have some questions before starting and also like some feedback on the ideas.
* Currently all the tests are in tests/ with only a subdirectory for fixtures. Is it good to let it match the src directory (so on this moment, add a Checks directory)
* Is it good to mock some protected parameters on the command to validate that? It is a way that I used to do but maybe there is a better solution
* Is a check that we get a value back sometimes enough or is it wanted to always validate the result? Like the name function on a check implementation?
* Any other to think about / know?

I like to have at least some answers from @mpociot because it is his project, but I'm happy with other input.

**Comment by mpociot** [comment]
I feel like some very simple checks - especially those that use PHP core functions such as `version_compare` do not really need to have automated tests.

At least it would highly increase the complexity of the checks. So we would create version compare classes, that we can then mock and inject to the check etc. but I don't think this is necessary for **all** tests, as we would still mock the core functionality and can't ensure it works.

So that being said - I'm happy for every test that we get for this, but for the very simple checks, I do not feel the explicit need.
