### ISSUE TITLE
Default locale checks are not correct (for Mac OS)

### ISSUE THREAD

**Issue by sdbruder** [beyondcode/laravel-self-diagnosis#55]
Default config is checking for en_US and en_US.utf8. that is not valid for Mac OS, the correct values for Mac OS will be en_US.UTF-8 instead.

**Comment by tvbeek** [comment]
I think you need then overwrite the config (see https://github.com/beyondcode/laravel-self-diagnosis#customization ) because if the en_US.UTF-8 will be added it will always fail.
On Mac OS it will miss the en_US.utf8 and on *nix systems it will miss the en_US.UTF-8 locale.

So my personal opinion is that it is a good default because the most servers will work with the defaults. But it is nice to have this issue to let other people find it.
